spring:
  profiles:
    default: dev
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/


server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    context-path: /member
logging:
  level:
    root: info
jwt:
  secret: e85cc606fb8c3327c79883e75bc67007ff556c8ac20a100ad13af7dd2d389da7
---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/member
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: trace
    root: info